FUNC: cortex_function.py
# ARGS: [['https://www.nytimes.com/2019/07/14/us/ice-immigration-raids.html'], ['https://www.nytimes.com/2019/07/16/nyregion/eric-garner-case-death-daniel-pantaleo.html']]
ARGS: [[1,2,3,4,5,6,7,8,9],[1,2,3,4,5]]
DEP_FUNCS: ()
MODULES: ()
CALLBACK: None
CALLBACK_ARGS: ()
GROUP: 'default'
