FUNC: cortex_function.py
ARGS: [['https://www.nytimes.com/2019/07/14/us/ice-immigration-raids.html?action=click&module=News&pgtype=Homepage']]
DEP_FUNCS: ()
MODULES: ()
CALLBACK: None
CALLBACK_ARGS: ()
GROUP: 'default'
